### ISSUE TITLE
OTMWebView seems to "substitute" previous UIWebView instances

### ISSUE THREAD

**Issue by jdesiloniz** [otium/OTMWebView#5]
Hi! First of all I wanted to congratulate you for your library, it brings on a lot of stuff that were really needed while working with UIWebView.

We implemented your library using CocoaPods the other day, and while the functionality we were expecting from it worked great, we found that in other view controllers that made no import to the OTMWebView class whatsoever previous UIWebView intances weren't working properly. We found that after putting the library in our project, it seems that UIWebView's delegate methods are like being "jammed" and they won't be called anymore. Maybe something is being done in the backs with KVO or NSNotificationCenter or something that can disrupt UIWebView delegates communication?

We verified this, as after uninstalling OTMWebView using Cocoapods, previous UIWebView instances started working right again.

Any clue?

Thanks!

**Comment by otium** [comment]
This issue should be fixed in a72d6ca02205ce75cc38c0ad7c10ae5cb3fe745f. When the delegate method was swizzled it swizzled all the UIWebView delegates, to fix it the delegate methods were implemented in OTMWebView.

**Comment by jdesiloniz** [comment]
Thanks!
